/** Common */
export const RESET_INITIAL_STATE = "RESET_INITIAL_STATE";
export const HANDLE_INPUT_CHANGE = "HANDLE_INPUT_CHANGE";
export const HANDLE_CHECKBOX_CHANGE = "HANDLE_CHECKBOX_CHANGE";
export const HANDLE_SELECT_CHANGE = "HANDLE_SELECT_CHANGE";
export const HANDLE_STEP_CHANGE = "HANDLE_STEP_CHANGE";
export const HANDLE_TAB_CHANGE = "HANDLE_TAB_CHANGE";
export const HANDLE_LOADING_REQUEST = "HANDLE_LOADING_REQUEST";
export const HANDLE_ERROR_REQUEST = "HANDLE_ERROR_REQUEST";
export const HANDLE_ERROR_WITH_MESSAGE_REQUEST =
  "HANDLE_ERROR_WITH_MESSAGE_REQUEST";
export const HANDLE_SUCCESS_REQUEST = "HANDLE_SUCCESS_REQUEST";

// PIZZA
export const HANDLE_SET_INITIAL_VALUE = "HANDLE_SET_INITIAL_VALUE";
export const HANDLE_RESET_CHECKBOX_CHANGE = "HANDLE_RESET_CHECKBOX_CHANGE";
export const HANDLE_CHANGE_FLAVOR = "HANDLE_CHANGE_FLAVOR";
export const HANDLE_RESET_FLAVOR = "HANDLE_RESET_FLAVOR";
export const HANDLE_VISIBLE_MODAL = "HANDLE_VISIBLE_MODAL";
export const HANDLE_ERROR_FINALIZED_PIZZA = "HANDLE_ERROR_FINALIZED_PIZZA";
export const HANDLE_SET_INITIAL_VALUE_RECOMMENDATION = "HANDLE_SET_INITIAL_VALUE_RECOMMENDATION";
export const HANDLE_RECOMMENDATION_VISIBLE_MODAL = "HANDLE_RECOMMENDATION_VISIBLE_MODAL";
export const HANDLE_RECOMMENDATION_LOADING_REQUEST = "HANDLE_RECOMMENDATION_LOADING_REQUEST";
export const HANDLE_RECOMMENDATION_SUCCESS_REQUEST = "HANDLE_RECOMMENDATION_SUCCESS_REQUEST";

